### ISSUE TITLE
Cannot find module context 

### ISSUE THREAD

**Issue by wontwon** [edwinv710/twilio-lambda-example#1]
Hi Ed! First, thanks so much for this writeup. I think its really helpful with getting me primered to use Lambda. I tried following along your tutorial but got stuck with running the lambda function locally. It is throwing an error:

```
Error: Cannot find module '../../context.json'
```

Is this most likely bc there have been updates to the package? Thank you.

**Comment by wontwon** [comment]
Might be because my package didn't install entirely :

**Comment by ejwwood** [comment]
Hi @wontwon and @edwinv710,

Thanks for posting this tutorial edwinv710!

I'm a total noob to both node.js and lambda and I also got stuck at the same spot:

Error: Cannot find module '../../../context.json'

I'm not understanding what you mean by "my package didn't install entirely".  
I've tried updating node to the latest version as well as reinstalling each module with npm but I get the same error.

When I put a blank context.json file in the project root, it throws an Unexpected end of input so it wants a file there, but I'm not sure what goes in it.

Any info to get me pointed in the right direction would be greatly appreciated.

thanks!

**Comment by yann-git** [comment]
Hi everyone,

my 3 cents (regarding the context.json error) :
1. read this : https://www.npmjs.com/package/node-lambda
2. and do that : `node-lambda setup`
> Setup done. Edit the .env, deploy.env, context.json and event.json files as needed.
3. replace 
`    to: my_phone_number,
    from: event.to,`
by
`    to: event.to,
    from: my_phone_number,`

It worked for me
Thank you @edwinv710
Cheers
